### ISSUE TITLE
Empty Screen On Samsung M Series

### ISSUE THREAD

**Issue by ardacuhadaroglu** [DeweyReed/UltimateMusicPicker#20]
Hello, 

Firstly thank you for your useful framework but some clients are saying that seeing empty screen when they open the ringtonepicker.

Samsung Galaxy M30s (m30s) Android 10.
Can you test it and fix it please? I do not want to change your framework :( 

Edit: I am using 2.0.6 version. I saw different issues on 3.x version so I choosed 2.0.6 version.

**Comment by DeweyReed** [comment]
The bug is weird and hard to fix. I've also received some complaints from users about the bug. That's why I added SAF support in the 3.0.

[Here's the code to get device ringtones in 2.0.6.](https://github.com/DeweyReed/UltimateRingtonePicker/blob/2.0.6/library/src/main/java/xyz/aprildown/ultimatemusicpicker/data/MusicModel.kt#L90) Can you find any potential bug?

**Comment by DeweyReed** [comment]
It seems a system problem. I'm closing it. Feel free to reopen it if you have more info.
