### ISSUE TITLE
[Feature Request] Follow the app dialog theme

### ISSUE THREAD

**Issue by adrcotfas** [DeweyReed/UltimateMusicPicker#26]
First of all, thanks for the library!

Unfortunately the library dialog doesn't use the app dialog theme as defined inside the `alertDialogTheme` or `materialAlertDialogTheme` items of the app theme.  
I tried using the following in `RingtonePickerDialog::onCreateDialog`:
```
return object : AppCompatDialog(requireContext(), R.attr.materialAlertDialogTheme) { ...
```
but this did not help to get a reference to the app dialog theme.  

If you have a direction in mind to fix this, I can support.

**Comment by DeweyReed** [comment]
It makes sense to me. I'll see what I can do.

**Comment by DeweyReed** [comment]
Because `RingtonePickerDialog` is a wrapper of `RingtonePickerFragment`, you could use `RingtonePickerFragment` directly and customize as much as you want.

https://github.com/DeweyReed/UltimateRingtonePicker/blob/master/library/src/main/java/xyz/aprildown/ultimateringtonepicker/RingtonePickerDialog.kt
